server:
  port: 80

logging:
  config: "classpath:logback-spring.xml"

spring:
  application:
    name: github-ci-test
  jpa:
    database: postgresql
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        hbm2ddl: none
        dialect: org.hibernate.dialect.PostgreSQLDialect
        order_inserts: true
        order_updates: true
        batch_versioned_data: true
        jdbc:
          batch_size: 100
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/todoit}?reWriteBatchedInserts=true
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: ${DB_HIKARI_MIN_IDLE:1}
      maximum-pool-size: ${DB_HIKARI_MAX_POOL_SIZE:10}
      auto-commit: ${DB_HIKARI_AUTO_COMMIT:true}
      idle-timeout: ${DB_HIKARI_IDLE_TIMEOUT:30000}
